"""Initial migration

Revision ID: 4bb8f8ddd003
Revises: 
Create Date: 2025-11-28 21:16:29.000187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb8f8ddd003'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freight_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('final_rate', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_table('freights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_id', sa.String(), nullable=True),
    sa.Column('loading_place', sa.String(), nullable=True),
    sa.Column('unloading_place', sa.String(), nullable=True),
    sa.Column('loading_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unloading_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cargo_info', sa.String(), nullable=True),
    sa.Column('price_original', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('rate_min', sa.Float(), nullable=True),
    sa.Column('rate_avg', sa.Float(), nullable=True),
    sa.Column('rate_max', sa.Float(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_deal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freights_id'), 'freights', ['id'], unique=False)
    op.create_index(op.f('ix_freights_trans_id'), 'freights', ['trans_id'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_freights_trans_id'), table_name='freights')
    op.drop_index(op.f('ix_freights_id'), table_name='freights')
    op.drop_table('freights')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
